version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: pentest-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-pentest}
      POSTGRES_USER: ${POSTGRES_USER:-pentest}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-SET_A_STRONG_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-pentest}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pentest-network

  # Neo4j (BloodHound)
  neo4j:
    image: neo4j:5-community
    container_name: pentest-neo4j
    environment:
      NEO4J_AUTH: ${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-SET_A_STRONG_PASSWORD}
      NEO4J_PLUGINS: '["apoc"]'
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7474"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pentest-network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: pentest-redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pentest-network

  # Ollama (Local AI)
  ollama:
    image: ollama/ollama:latest
    container_name: pentest-ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - pentest-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # Uncomment if you have GPU:
    # devices:
    #   - /dev/dri:/dev/dri

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pentest-backend
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB:-pentest}
      - POSTGRES_USER=${POSTGRES_USER:-pentest}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-SET_A_STRONG_PASSWORD}
      - NEO4J_HOST=neo4j
      - NEO4J_PORT=7687
      - NEO4J_USER=${NEO4J_USER:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-SET_A_STRONG_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    networks:
      - pentest-network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # Celery Worker
  celery-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pentest-celery-worker
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    depends_on:
      - postgres
      - redis
    networks:
      - pentest-network
    command: celery -A app.core.celery_app worker --loglevel=info

  # Celery Beat (Scheduler)
  celery-beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pentest-celery-beat
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    depends_on:
      - postgres
      - redis
    networks:
      - pentest-network
    command: celery -A app.core.celery_app beat --loglevel=info

  # Main Pentest Container (Kali)
  pentest:
    build:
      context: ./container
      dockerfile: Containerfile
    container_name: pentest-kali
    privileged: true  # Required for some pentesting tools
    network_mode: "host"  # For network scanning
    volumes:
      - ./data:/data
      - pentest_tools:/opt/pentest
    environment:
      - START_NEO4J=false  # Neo4j runs in separate container
    networks:
      - pentest-network
    # Keep container running
    command: tail -f /dev/null

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pentest-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_WS_URL=ws://localhost:8000
    depends_on:
      - backend
    networks:
      - pentest-network
    command: npm start

volumes:
  postgres_data:
  neo4j_data:
  neo4j_logs:
  redis_data:
  ollama_data:
  backend_data:
  pentest_tools:

networks:
  pentest-network:
    driver: bridge
